version: "3"

services:
  api-server:
    build:
      context: .
      dockerfile: ./backend/api-server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python3 manage.py migrate;
             python3 manage.py runserver 0.0.0.0:8000"

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./backend/api-document.yaml:/api/api-document.yaml:ro
    ports:
      - 127.0.0.1:3000:8080

  slack-app:
    build:
      context: .
      dockerfile: ./slack_app/slack_Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./slack_app:/slack_app
    command: >
      sh -c "python3 ./src/bot.py"
